### ISSUE TITLE
请问你这个事基于ant design pro 哪个版本做的

### ISSUE THREAD

**Issue by whaty** [Jkanon/webmagician-ui#1]
您好：
   从您的这个项目学到了很多东西，请问你这个事基于ant design pro 哪个版本做的？

**Comment by Jkanon** [comment]
基于v4的版本做的，但是一开始也是从v2开始接触的，所以有些残留的js代码就是那时候的产物。

**Comment by Jkanon** [comment]
> 您好：
> 从您的这个项目学到了很多东西，请问你这个事基于ant design pro 哪个版本做的？

基于v4的版本做的，但是一开始也是从v2开始接触的，所以有些残留的js代码就是那时候的产物。
