### ISSUE TITLE
关于columns等定义在index.tsx中导致文件过长

### ISSUE THREAD

**Issue by whaty** [Jkanon/webmagician-ui#2]
你好，如果所有colums都定义在index.tsx中，会导致文件过长，不太简洁，有没有办法把涉及到colums的定义（列表中的column,新增修改时的cloumn），都放到另外一个文件谢谢！！
![image](https://user-images.githubusercontent.com/26294919/71238448-0874b700-233f-11ea-8e2f-df23d799a68c.png)

**Comment by Jkanon** [comment]
可以的，这就是个变量。你可以把它定义在另外一个文件中，然后在index.tsx中导入进来

**Comment by whaty** [comment]
能不能做个例子，就用你的这个开原项目😇




    


在2019年12月26日 08:38，Jkanon 写道： 可以的，这就是个变量。你可以把它定义在另外一个文件中，然后在index.tsx中导入进来

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Jkanon/webmagician-ui/issues/2?email_source=notifications\u0026email_token=AGITVB6THBMK6F5GARBOYCLQ2P4HTA5CNFSM4J5ZOYF2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHUVV7I#issuecomment-568941309",
"url": "https://github.com/Jkanon/webmagician-ui/issues/2?email_source=notifications\u0026email_token=AGITVB6THBMK6F5GARBOYCLQ2P4HTA5CNFSM4J5ZOYF2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHUVV7I#issuecomment-568941309",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Jkanon** [comment]
你看下[这个](https://github.com/Jkanon/webmagician-ui/blob/master/src/pages/Crawler/RuleConf/components/PageRegion.tsx#L9)的定义和用法，类似的。
